ecoshare/ecoshare/urls.py
from django.contrib import admin
from django.urls import path
from core import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('cadastro/', views.CadastroView.as_view(), name='cadastro'),
    path('homeCliente/', login_required(views.HomeClienteView.as_view()), name='homeCliente'),
    path('relatorioCliente/', login_required(views.RelatorioClienteView.as_view()), name='relatorioCliente'),
    path('doacoesCliente/', login_required(views.DoacoesClienteView.as_view()), name='doacoesCliente'),
    path('brindesCliente/', login_required(views.BrindesClienteView.as_view()), name='brindesCliente'),
    path('perfilCliente/', login_required(views.PerfilClienteView.as_view()), name='perfilCliente'),
    path('editPerfilCliente/', login_required(views.EditPerfilClienteView.as_view()), name='editPerfilCliente'),
    path('logout/', views.LogoutView, name='logout'),
]

ecoshare/core/models.py
from django.db import models
from django.core import validators
from djongo import models as djongo_models
from django.contrib.auth.models import User


class EnderecoModel(models.Model):
    _id = djongo_models.ObjectIdField()
    cep = models.CharField(max_length=9, validators=[validators.RegexValidator(regex='^\\d{5}-\\d{3}$')])
    rua = models.CharField(max_length=100)
    bairro = models.CharField(max_length=50)
    numero = models.CharField(max_length=10)
    cidade = models.CharField(max_length=50)
    estado = models.CharField(max_length=50)
    pais = models.CharField(max_length=50)
    
    def __str__(self):
        """Devolve uma representação em string do modelo."""
        return self._id

    class Meta:
        verbose_name = 'Endereco'
        verbose_name_plural = 'Enderecos'

class DoacaoModel(models.Model):
    _id = djongo_models.ObjectIdField()
    material_doado = models.CharField(max_length=50)
    peso = models.IntegerField(validators=[validators.MinValueValidator(1)])
    data = models.DateTimeField(auto_now_add=True)
    item_recebido = models.CharField(max_length=50)
    validacao = models.BooleanField(default=False)
    
    def __str__(self):
        """Devolve uma representação em string do modelo."""
        return self.material_doado

    class Meta:
        verbose_name = 'Doacao'
        verbose_name_plural = 'Doacoes' # Para quando forem realizadas diversas doações

class UsuarioModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    nome_completo = models.CharField(max_length=100)
    cpf = models.CharField(max_length=14, validators=[validators.RegexValidator(regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])
    email = models.EmailField(unique=True)
    senha = models.CharField(max_length=100)
    telefone = models.CharField(max_length=15, validators=[validators.RegexValidator(regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')])
    data_nascimento = models.DateField()
    endereco = djongo_models.EmbeddedField(model_container=EnderecoModel)
    doacoes = djongo_models.ArrayField(model_container=DoacaoModel)

    def __str__(self):
        """Devolve uma representação em string do modelo."""
        return self.nome_completo

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'
        db_table = 'ecoshare'  # Define o nome da coleção no MongoDB

ecoshare/core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import EnderecoModel, DoacaoModel, UsuarioModel
from django.contrib.auth.forms import UserCreationForm

class EnderecoForm(forms.ModelForm):
    class Meta:
        model = EnderecoModel
        fields = ['cep', 'rua', 'bairro', 'numero', 'cidade', 'estado', 'pais']

class DoacaoForm(forms.ModelForm):
    class Meta:
        model = DoacaoModel
        fields = ['_id', 'material_doado', 'peso', 'data', 'item_recebido', 'validacao']
        labels = {
            'material_doado': 'Material Doado',
            'peso': 'Peso',
            'data': 'Data',
            'item_recebido': 'Item Recebido',
        }

class UsuarioForm(UserCreationForm):
    data_nascimento = forms.DateField(
        widget=forms.DateInput(
            format=('%d/%m/%Y'),
            attrs={
                'class': 'form-control',
                'placeholder': 'Data de Nascimento',
                'type': 'date'
            }
        )
    )

    class Meta:
        model = UsuarioModel
        fields = ['nome_completo', 'cpf', 'email', 'telefone', 'data_nascimento', 'endereco', 'doacoes']
        labels = {
            'nome_completo': 'Nome Completo',
            'cpf': 'CPF',
            'email': 'Email',
            'telefone': 'Telefone',
            'data_nascimento': 'Data de Nascimento',
            'endereco': 'Endereço',
            'doacoes': 'Doações',
        }

    def clean_nome_completo(self):
        nome_completo = self.cleaned_data['nome_completo']
        return nome_completo.upper().strip()

    def clean_cpf(self):
        cpf = self.cleaned_data['cpf']
        cpf = cpf.strip()
        if len(cpf) == 11:
            return cpf
        raise ValidationError('Insira um CPF válido no formato 999.999.999-99.')
    
    def clean_email(self):
        email = self.cleaned_data['email']
        return email

    def clean_telefone(self):
        telefone = self.cleaned_data['telefone']
        if telefone:
            return telefone
        raise ValidationError('Insira um telefone válido no formato (99) 99999-9999 ou (99) 9999-9999.')

    def clean_endereco(self):
        endereco = self.cleaned_data['endereco']
        return endereco
    
    def clean_doacoes(self):
        doacoes = self.cleaned_data['doacoes']
        return doacoes

ecoshare/core/views.py
from django.contrib import messages
from django.views import View
from django.shortcuts import render
from .models import UsuarioModel, DoacaoModel
from bson import ObjectId
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse
from django.urls import reverse
from django.shortcuts import get_object_or_404

import secrets
import string

class IndexView(View):
    template_name = 'index.html'
    
    def get(self, request):
        return render(request, self.template_name)
    
class CadastroView(View):
    template_name = 'cadastro.html'
    
    def get(self, request):
        return render(request, self.template_name)
    
    def post(self, request):
        # Obtenha os dados do formulário
        nome_completo = request.POST.get('nome_completo')
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        cpf = request.POST.get('cpf')

        try:
            # Verifique se já existe um usuário com o mesmo e-mail ou CPF
            if User.objects.filter(username=email).exists() or UsuarioModel.objects.filter(cpf=cpf).exists():
                messages.error(request, 'Já existe um usuário com este email ou CPF cadastrado.')
                return render(request, self.template_name)

            # Cria o usuário se não houver duplicidade
            user = User.objects.create_user(username=email, email=email)
            user.set_password(senha)
            user.save()

            endereco_dict = {
                "_id": str(ObjectId()),
                "cep": request.POST['cep'],
                "rua": request.POST['rua'],
                "bairro": request.POST['bairro'],
                "numero": request.POST['numero'],
                "cidade": request.POST['cidade'],
                "estado": request.POST['estado'],
                "pais": request.POST['pais']
            }

            usuario = UsuarioModel(
                user=user,
                nome_completo=request.POST['nome_completo'],
                cpf=request.POST['cpf'],
                email=request.POST['email'],
                senha=request.POST['senha'],
                telefone=request.POST['telefone'],
                data_nascimento=request.POST['data_nascimento'],
                endereco=endereco_dict,
                doacoes=[]
            )
            usuario.save()

            return HttpResponseRedirect(reverse('homeCliente'))

        except Exception as e:
            # Capture qualquer exceção para diagnóstico
            messages.error(request, "Erro ao cadastrar usuário. Por favor, contate o suporte do sistema para assistência.")
            return render(request, self.template_name)
    
class LoginView(View):
    template_name = 'login.html'
    
    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        
        user = authenticate(username=email, password=senha)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('homeCliente'))
        else:
            # Caso o usuário insira informações erradas
            messages.info(request, 'E-mail ou senha incorretos.')
            return render(request, self.template_name)

def LogoutView(request):
    """Faz logout do usuário."""
    logout(request)
    return HttpResponseRedirect(reverse('index'))
        
class HomeClienteView(View):
    template_name = 'homeCliente.html'

    def get(self, request):
        nome = get_object_or_404(UsuarioModel, user=request.user)
        return render(request, self.template_name, {'nome': nome})
    
    def get(self, request):
        usuario = get_object_or_404(UsuarioModel, user=request.user)
        quantidade_doacoes = len(usuario.doacoes)
        
        # filtra as doacoes validadas
        doacoes_validadas = [doacao for doacao in usuario.doacoes if doacao.get('validacao') is True]
        qtd_doacoes_validadas = len(doacoes_validadas)

        return render(request, self.template_name, {
            'nome': usuario,
            'quantidade_doacoes': quantidade_doacoes,
            'qtd_doacoes_validadas': qtd_doacoes_validadas
        })
    


def generate_random_password():
    # Define os caracteres permitidos (letras minúsculas, dígitos e caracteres especiais)
    allowed_chars = string.ascii_letters + string.digits + "!@#$%&"

    # Gera uma senha aleatória com 6 caracteres
    random_password = ''.join(secrets.choice(allowed_chars) for _ in range(6))

    return random_password

class RelatorioClienteView(View):
    template_name = 'relatorioCliente.html'

    def get(self, request):
        usuario = get_object_or_404(UsuarioModel, user=request.user)
        doacoes = usuario.doacoes

        filtro_status = request.GET.get('status')
        if filtro_status == 'retirado':
            doacoes = [doacao for doacao in doacoes if doacao.get('validacao')]
        elif filtro_status == 'pendente':
            doacoes = [doacao for doacao in doacoes if not doacao.get('validacao')]

        for doacao in doacoes:
            doacao['id'] = doacao.pop('_id')

        senha_aleatoria = generate_random_password()

        context = {
            'doacoes': doacoes,
            'senha_aleatoria': senha_aleatoria,
        }
        return render(request, self.template_name, context)
    
    def post(self, request):
        action = request.POST.get('action')
        doacao_id = request.POST.get('doacao_id')

        if action == 'delete' and doacao_id:
            try:
                usuario = UsuarioModel.objects.get(user=request.user)

                # Filtro de doações para remover a doação com o id especificado
                doacoes_atualizadas = [doacao for doacao in usuario.doacoes if str(doacao['_id']) != doacao_id]

                UsuarioModel.objects.filter(user=request.user).update(doacoes=doacoes_atualizadas)

            except UsuarioModel.DoesNotExist:
                messages.error(request, "Usuário não encontrado.")
        return HttpResponseRedirect(reverse('relatorioCliente'))

class DoacoesClienteView(LoginRequiredMixin, View):
    template_name = 'doacoesCliente.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        # Obtendo os dados do formulário
        material_doado = request.POST.get('material')
        peso = request.POST.get('peso')
        data = request.POST.get('data')
        item_recebido = request.POST.get('brinde')

        # Criando uma nova instância de DoacaoModel
        doacao = DoacaoModel(
            _id=ObjectId(),
            material_doado=material_doado,
            peso=peso,
            data=data,
            item_recebido=item_recebido,
            validacao=False  # Sempre inicializado como falso
        )

        # Salvando a nova doação
        doacao.save()

        # Converte a instância de doação para um dicionário
        doacao_dict = {
            "_id": doacao._id,
            "material_doado": doacao.material_doado,
            "peso": doacao.peso,
            "data": doacao.data,
            "item_recebido": doacao.item_recebido,
            "validacao": doacao.validacao
        }

        try:
            # Obtendo o usuário
            usuario = UsuarioModel.objects.get(user=request.user)
            
            # Usando o método update para adicionar a doação
            UsuarioModel.objects.filter(user=request.user).update(
                doacoes=[*usuario.doacoes, doacao_dict]
            )

        except UsuarioModel.DoesNotExist:
            # Se o usuário não existir, criar um novo
            usuario = UsuarioModel(
                user=request.user,
                doacoes=[doacao_dict]
            )
            usuario.save()

        # Redirecionando de volta para a página de doações
        return HttpResponseRedirect(reverse('relatorioCliente'))
        
class BrindesClienteView(View):
    template_name = 'brindesCliente.html'

    def get(self, request):
        return render(request, self.template_name)

class PerfilClienteView(LoginRequiredMixin, TemplateView):
    template_name = 'perfilCliente.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        usuario = get_object_or_404(UsuarioModel, user=self.request.user)
        context['usuario'] = usuario
        return context
    
class EditPerfilClienteView(LoginRequiredMixin, TemplateView):
    template_name = 'editPerfilCliente.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        usuario = get_object_or_404(UsuarioModel, user=self.request.user)
        context['usuario'] = usuario
        return context

    def post(self, request):
        usuario = get_object_or_404(UsuarioModel, user=request.user)
        
        # Obtenha os dados do formulário
        nome_completo = request.POST.get('nome_completo')
        cpf = request.POST.get('cpf')
        email = request.POST.get('email')
        telefone = request.POST.get('telefone')
        data_nascimento = request.POST.get('data_nascimento')
        senha = request.POST.get('senha')

        # Pegue o _id do endereço existente
        endereco_id = usuario.endereco['_id']
        
        endereco_dict = {
            "_id": endereco_id,  # Certifique-se de que o _id está incluído
            "cep": request.POST.get('cep'),
            "rua": request.POST.get('rua'),
            "bairro": request.POST.get('bairro'),
            "numero": request.POST.get('numero'),
            "cidade": request.POST.get('cidade'),
            "estado": request.POST.get('estado'),

ecoshare/core/templates/brindesCliente.html
{% load static %}
 
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Estilo customizado -->
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Bootstrap Icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <!-- ICONE -->
    <link rel="icon" href="../static/img/icon.png">
    <!-- Título -->
    <title>Brindes disponíveis</title>
</head>
 
<body>

<!-- sidebar -->
<div class="sidebar">
    <a href="{% url 'index' %}"><img src="../static/img/Logo Ecoshare branco.png" alt="Logo" width="120"></a>
    <hr>
    <a href="{% url 'homeCliente' %}"><i class="bi bi-house-door-fill"></i> Home</a>
    <a href="{% url 'doacoesCliente' %}"><i class="bi bi-cart-check"></i> Nova doação</a>
    <a class="active" href="{% url 'brindesCliente' %}"><i class="bi bi-gift"></i> Brindes disponíveis</a>
    <a href="{% url 'relatorioCliente' %}"><i class="bi bi-bar-chart-line"></i> Minhas doações</a>
    <a href="{% url 'perfilCliente' %}"><i class="bi bi-person-fill"></i> Perfil</a>
    <hr>
    <a href="{% url 'logout' %}"><i class="bi bi-door-open"></i> Sair</a>
</div>
  
<!-- Conteúdo -->

<div id="brindes" class="content">
    <div class="card">
        <div class="row">
            <div class="col-md-12">
                <h5>Brindes disponíveis</h5>
            </div>
            <div class="col-sm-6">
                <div class="card inner-card" style="width: 18rem;">
                    <img class="card-img-top" src="https://us.123rf.com/450wm/topntp/topntp1806/topntp180600513/102427979-arroz-de-jasmim-tailand%C3%AAs-cru-branco.jpg?ver=6" alt="Arroz">
                    <div class="card-body text-center">
                        <h6 class="card-text">Arroz</h6>
                        <p class="card-text">Peso do pacote - 5KG</p>
                        <button class="btn btn-custom"><a href="{% url 'relatorioCliente' %}" class="nav-link">Resgatar</a></button>
                    </div>
                </div>
                <div class="card inner-card" style="width: 18rem;">
                    <img class="card-img-top" src="https://img.freepik.com/free-photo/pasta-wooden-cups-black-surface_114579-16267.jpg?t=st=1716991012~exp=1716994612~hmac=9c12f9b059cf55c50cb2e8edbe980c07c4f7ae1996cd9ff4f45d14262d51c51f&w=740" alt="Macarrão">
                    <div class="card-body text-center">
                        <h6 class="card-text">Macarrão</h6>
                        <p class="card-text">Peso do pacote - 1KG</p>
                        <button class="btn btn-custom"><a href="{% url 'relatorioCliente' %}" class="nav-link">Resgatar</a></button>
                    </div>
                </div> 
            </div>
            <div class="col-sm-6">
                <div class="card inner-card" style="width: 18rem;">
                    <img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4sxO9RPm-S3H6h7Yy0GUiPMwxXmCaHWbUzwx3RHaVOz-9_BqBPYgNKvvAC8KgwyWT_N0&usqp=CAU" alt="Feijão">
                    <div class="card-body text-center">
                        <h6 class="card-text">Feijão</h6>
                        <p class="card-text">Peso do pacote - 2KG</p>
                        <button class="btn btn-custom"><a href="{% url 'relatorioCliente' %}" class="nav-link">Resgatar</a></button>
                    </div>
                </div>
                <div class="card inner-card" style="width: 18rem;">
                    <img class="card-img-top" src="https://img.freepik.com/fotos-gratis/vista-superior-de-diferentes-tipos-e-formas-de-acucar-em-uma-tigela-e-copos-em-fundo-preto-de-madeira_141793-7631.jpg" alt="Açúcar">
                    <div class="card-body text-center">
                        <h6 class="card-text">Açúcar</h6>
                        <p class="card-text">Peso do pacote - 1KG</p>
                        <button class="btn btn-custom"><a href="{% url 'relatorioCliente' %}" class="nav-link">Resgatar</a></button>
                    </div>
                </div>          
            </div>
        </div>
    </div>
</div>

</body>
 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>

ecoshare/core/templates/cadastro.html
{% load static %}
 
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Estilo customizado -->
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- ICONE -->
    <link rel="icon" href="../static/img/icon.png">
    <!-- Título -->
    <title>EcoShare | Entre ou Cadastre-se</title>
</head>
<body>

<!-- Info incorreta -->
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-dismissible fade show custom-alert mb-0" role="alert">
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message | safe }}
            </p>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
<!-- End - Info incorreta -->

<!-- End - Info de duas pessoas batendo -->
<div id="cadastro" class="container-fluid">
    <div class="row h-100">
        <div class="col-md-6 gx-0">
            <div id="left">
                
            </div>
        </div>
        <div class="col-sm-6 gx-0">
            <div id="right">
            <!--Navbar-->
            <nav class="navbar navbar-expand-md">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'login' %}" class="nav-link mr-3">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'cadastro' %}" class="nav-link active ml-3">Cadastre-se</a>    
                    </li>
                </ul>
            </nav>

            <form action="{% url 'cadastro' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="action" value="cadastrar">
                <div class="row">
                    <div class="col-sm-6"> 
                        <label for="nome" class="mb-2">Nome completo</label>                    
                        <input class="form-control mb-3" type="text" name="nome_completo" required>
                        <label for="date" class="mb-2">Data de nascimento</label> 
                        <input class="form-control mb-3" type="date" name="data_nascimento" value="31-03-2020" id="id_data" required>
                        <label for="cep" class="mb-2">CEP</label>  
                        <input class="form-control mb-3" type="text" name="cep" id="cep" required>
                        <label for="numero" class="mb-2">Número</label>                       
                        <input class="form-control mb-3" type="number" name="numero" required>                 
                    </div>
                    <div class="col-sm-6">
                        <label for="cpf" class="mb-2">CPF</label>                        
                        <input class="form-control mb-3" type="number" name="cpf" required>
                        <label for="telefone" class="mb-2">Telefone</label> 
                        <input class="form-control mb-3" type="number" name="telefone" required>
                        <label for="rua" class="mb-2">Rua</label>     
                        <input class="form-control mb-3" type="text" name="rua" id="rua" required> 
                        <label for="bairro" class="mb-2">Bairro</label> 
                        <input class="form-control mb-3" type="text" name="bairro" id="bairro" required>    
                    </div>
                    <div class="col-sm-4">
                        <label for="cidade" class="mb-2">Cidade</label> 
                        <input class="form-control mb-3" type="text" name="cidade" id="cidade" required>  
                    </div>
                    <div class="col-sm-4">  
                        <label for="estado" class="mb-2">Estado</label>                   
                        <input class="form-control mb-3" type="text" name="estado" id="estado" required>  
                    </div>
                    <div class="col-sm-4">
                        <label for="pais" class="mb-2">País</label>
                        <input class="form-control mb-3" type="text" name="pais" id="pais" required>                   
                    </div>
                    <div class="col-sm-6">
                        <label for="email" class="mb-2">E-mail</label> 
                        <input class="form-control mb-2" type="email" name="email" required>
                    </div>
                    <div class="col-sm-6">
                        <label for="senha" class="mb-2">Senha</label> 
                        <input class="form-control mb-2" type="password" name="senha" required>
                    </div>
                    <div class="col-sm-12">
                        <button type="submit" class="btn btn-custom mt-2 mb-3">Cadastrar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="{% static 'js/cadastro.js' %}"></script>
</html>

ecoshare/core/templates/doacoesCliente.html
{% load static %}
 
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Estilo customizado -->
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Bootstrap Icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <!-- ICONE -->
    <link rel="icon" href="../static/img/icon.png">
    <!-- Título -->
    <title>Cadastro de doação</title>
</head>
<body>

<!-- sidebar -->
<div class="sidebar">
    <a href="{% url 'index' %}"><img src="../static/img/Logo Ecoshare branco.png" alt="Logo" width="120"></a>
    <hr>
    <a href="{% url 'homeCliente' %}"><i class="bi bi-house-door-fill"></i> Home</a>
    <a class="active" href="{% url 'doacoesCliente' %}"><i class="bi bi-cart-check"></i> Nova doação</a>
    <a href="{% url 'brindesCliente' %}"><i class="bi bi-gift"></i> Brindes disponíveis</a>
    <a href="{% url 'relatorioCliente' %}"><i class="bi bi-bar-chart-line"></i> Minhas doações</a>
    <a href="{% url 'perfilCliente' %}"><i class="bi bi-person-fill"></i> Perfil</a>
    <hr>
    <a href="{% url 'logout' %}"><i class="bi bi-door-open"></i> Sair</a>
</div>
<!-- End - sidebar -->
<!-- form doação -->
<div id="doacao" class="content">
    <div class="card">
        <form action="" method="post">
            {% csrf_token %}
            <h5>Cadastrar doação</h5>
            <input type="hidden" name="action" value="cadastrar">
            <div class="row" id="itens">
                <div class="col-sm-6"> 
                    <label for="data">Data</label>                   
                    <input class="form-control mb-3" type="date" name="data" id="data" placeholder="Data da doação" disabled readonly>       
                    <label for="material">Material</label>
                    <select class="form-control mb-3" name="material" id="material" required>
                        <option value="" disabled selected>Selecione</option>
                        <option value="Garrafa Pet">Garrafa Pet</option>
                        <option value="Detergente">Detergente</option>
                        <option value="Amaciante">Amaciante</option>
                        <option value="Shampoo">Shampoo</option>
                    </select>
                    <label for="peso">Peso</label> 
                    <select class="form-control mb-3" name="peso" id="peso" required>
                        <option value="" disabled selected>Selecione</option>
                        <option value="2">2KG</option>
                        <option value="3">3KG</option>
                        <option value="4">4KG</option>
                        <option value="5">5KG</option>
                    </select>  
                    <label for="brinde">Brinde selecionado para troca</label>
                    <select class="form-control mb-3" name="brinde" id="brinde" required>
                        <option value="" disabled selected>Selecione</option>
                        <option value="Arroz">Arroz</option>
                        <option value="Feijão">Feijão</option>
                        <option value="Macarrão">Macarrão</option>
                        <option value="Açúcar">Açúcar</option>
                    </select>  
                    <div class="col-sm-12 mb-3">
                        <input type="checkbox" class="" id="termos" name="termos" required>
                        <label for="termos" class="form-check-label"> Eu confirmo a doação dos materiais em bom estado</label>
                    </form>
                </div>
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-custom mt-3">Salvar</button>
                </div>           
                </div>
            </div>
        </form>
    </div>
</div>
<!-- End - form doação -->

<script src="{% static 'js/data-doacao.js' %}"></script>

</body>
 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>